const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const element=()=>({value:'',textContent:'',innerHTML:'',hidden:false,classList:{add(){},remove(){}},setAttribute(){},focus(){},insertAdjacentHTML(){},addEventListener(){}});
const elements=new Map();const doc={getElementById(id){if(!elements.has(id))elements.set(id,element());return elements.get(id)},addEventListener(){}};
const map={setView(){return this},fitBounds(){this.fits=(this.fits||0)+1}};
const layer=()=>({addTo(){return this},clearLayers(){},bindPopup(){},bindTooltip(){},on(){},setStyle(style){this.style={...this.style,...style}},bringToFront(){}});
const context=vm.createContext({console,document:doc,L:{map:()=>map,tileLayer:layer,layerGroup:layer,polyline:layer,circleMarker:layer}});
vm.runInContext(fs.readFileSync('assets/app.js','utf8').replace(/loadData\(\);\s*$/,''),context);
context.copiesText=fs.readFileSync('data/expanded/tables/mei-copies.csv','utf8');context.stationsText=fs.readFileSync('data/expanded/tables/mei-itinerary-stations-resolved.csv','utf8');context.assert=assert;
vm.runInContext(`
state.copies=parseCsv(copiesText).filter(directCopy);
for(const s of parseCsv(stationsText)){if(!state.stationsByCopy.has(s.copy_id))state.stationsByCopy.set(s.copy_id,[]);state.stationsByCopy.get(s.copy_id).push(s)}
for(const a of state.stationsByCopy.values())a.sort((a,b)=>Number(a.source_order)-Number(b.source_order)||Number(a.place_order_within_source)-Number(b.place_order_within_source));
state.copies.forEach(c=>state.selected.add(c.copy_id));
assert.equal(state.copies.length,484);assert.equal(state.selected.size,484);
assert.equal(locationAtYear('00201166',2026).station.time_start,'1905');
assert.equal(locationAtYear('00201167',2026).station.location_label,'Rom');
assert.equal(locationAtYear('00201576',2026).station.time_start,'2024');
assert.equal(locationAtYear('02125950',2026).station.time_start,'2018');
for(const c of state.copies){const p=printStation(c.copy_id);assert.ok(p);const y=stationAnchor(p);if(y!==null){assert.equal(locationAtYear(c.copy_id,y-1),null);assert.equal(routeAtYear(c.copy_id,y-1).length,0)}}
assert.equal(copyStations('00200668').find(s=>s.station_type==='print_place').spatial_precision,'country');
assert.ok(!routeAtYear('02013229',1930).some(s=>s.date_warning));
for(const year of [1450,1499,1600,1800,1950,2026]){state.year=year;render();}
state.search='bologna';assert.ok(filteredCopies().length>0);state.search='';
for(const c of state.copies)openDetail(c.copy_id);
assert.equal(map.fits,undefined); // Opening details or moving time never resets the map.
assert.ok(popupHtml(state.copies[0]).includes('Druck verfolgen'));
state.year=2026;render();
const first=state.layers.find(x=>!x.marker&&x.copyId);focusCopy(first.copyId);
assert.equal(first.layer.style.weight,6);
assert.equal(state.layers.find(x=>x.marker&&x.copyId!==first.copyId).layer.style.opacity,.12);
updateRouteFocus();assert.equal(first.layer.style.weight,6);
render({list:false});assert.equal(state.focusedCopy,first.copyId);
focusCopy(null);assert.equal(state.layers[0].layer.style.opacity,.55);
const hoveredId=state.layers.find(x=>state.layers.filter(y=>y.copyId===x.copyId&&!y.marker).length>1).copyId;
hoverCopy(hoveredId);
assert.ok(state.layers.filter(x=>x.copyId===hoveredId&&!x.marker).every(x=>x.layer.style.weight===6));
assert.ok(state.layers.filter(x=>x.marker&&x.copyId!==hoveredId).every(x=>x.layer.style.opacity===.12));
assert.equal(els['clear-focus'].hidden,true);
const lockedId=state.layers.find(x=>x.copyId!==hoveredId).copyId;
focusCopy(lockedId);hoverCopy(hoveredId);hoverCopy(null);
assert.ok(state.layers.filter(x=>x.copyId===lockedId).every(x=>x.layer.style.opacity===1));
focusCopy(null);hoverCopy(hoveredId);hoverCopy(null);
assert.ok(state.layers.every(x=>x.layer.style.opacity===.55));
const groups=bundleRoutes(state.copies,2026);
assert.ok(groups.some(g=>g.entries.size>=23));
assert.equal(new Set(groups.map(g=>g.key)).size,groups.length);
for(const g of groups) assert.equal(g.entries.size,new Set([...g.entries.values()].map(e=>e.copy.copy_id)).size);
const one=state.copies.find(c=>routeAtYear(c.copy_id,2026).length>2);
assert.ok(bundleRoutes([one],2026).every(g=>g.entries.size===1));
assert.equal(bundleRoutes(state.copies,1450).length,0);
const shared=groups.find(g=>g.entries.size>2);
assert.equal((bundlePopup(shared).match(/data-track-id=/g)||[]).length,shared.entries.size);
state.focusedBundle=new Set(shared.entries.keys());updateRouteFocus();
assert.equal(els['clear-focus'].hidden,false);
focusCopy([...shared.entries.keys()][0]);assert.equal(state.focusedBundle,null);
const fake={copy_id:'test-repeat'};
const stop=(latitude,longitude,source_order)=>({latitude,longitude,source_order:String(source_order),station_type:'provenance_place',time_start:'1500',time_end:'1500'});
state.stationsByCopy.set(fake.copy_id,[stop('10','20',0),stop('30','40',1),stop('10','20',2),stop('30','40',3)]);
const repeated=bundleRoutes([fake],2026);
assert.equal(repeated.length,1);assert.equal(repeated[0].entries.size,1);assert.equal(repeated[0].entries.get(fake.copy_id).legs.length,3);
state.stationsByCopy.delete(fake.copy_id);
const a={source_order:'0',time_start:'1500',time_end:'1505'},b={source_order:'1',time_start:'1505',time_end:'1510'};
assert.equal(segmentEvidence(a,b,[a,b]).dashed,false);
assert.equal(segmentEvidence(a,{...b,time_start:'1550'},[a,b]).dashed,true);
assert.equal(segmentEvidence(a,{...b,spatial_precision:'country'},[a,b]).dashed,true);
assert.equal(segmentEvidence(a,{...b,time_start:''},[a,b]).dashed,true);
`,context);
console.log('PASS: full data rendering with Leaflet/DOM stubs; all 484 detail views, six slider years, pre-print dates, historic endpoints, filters, country point, date conflict and viewport.');
